jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - continue-on-error: true
      name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: /home/runner/work/Grim/Grim/build/libs/**.jar
name: Gradle Package
on:
  repository_dispatch:
    types: trigger-ga___gradle-publish.yml
